# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: true


    esi: true
    fragments: true
    
    http_client:
        scoped_clients:
            pokeApiClient: 
                base_uri: 'https://pokeapi.co'
                headers:
                    Accept: 'application/json'


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
